### ISSUE TITLE
Sentry Health is smaller than it should be on the Building UI

### ISSUE THREAD

**Issue by Shtuffs** [raysfire/rayshud#155]
Sometimes the hud displaying the buildings are positioned in a way where it covers up the chat. Also, the sentry health is too small: 

![image](https://user-images.githubusercontent.com/46979803/93724205-f399ae00-fb72-11ea-9785-2df43199f2ad.png)

**Comment by Shtuffs** [comment]
(I couldn't really reproduce it but the hud sometimes was just positioned more upwards, covering up the chat completely

**Comment by CriticalFlaw** [comment]
That's a known game bug that's fixed by inputting `hud_reloadscheme` into console.

**Comment by Shtuffs** [comment]
> 
> 
> That's a known game bug that's fixed by inputting `hud_reloadscheme` into console.

Reloading the hud still doesn't fix the problem where the sentry health is shown way too small

**Comment by CriticalFlaw** [comment]
Sentry health being small isn't a bug that reloadscheme would fix. I'll look into it later.

**Comment by CriticalFlaw** [comment]
Slightly tweaked the Engineer building UI. The health indicator should now be properly sized as well. Please check again and if it looks good, closed the issue.
